service: node-serverless-testing
plugins:
  - serverless-apigw-binary
  - serverless-offline
provider:
  name: aws
  runtime: nodejs16.x
  region: ap-south-1
  memorySize: 192
  timeout: 20
package:
  exclude:
    - .git

  include:
    - "node_modules"
    - "app.js"
    - "lambda.js"
custom:
  apigwBinary:
  types:
    - "*/*"
functions:
 api:
  handler: lambda.handler
  events:
      - http: GET {proxy+}
      - http: GET /
