service: node-serverless-testing
frameworkVersion: "3"
plugins:
  - serverless-offline
provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1
  memorySize: 192
  timeout: 20
  stage: dev
  deploymentBucket:
    name: shiv-source-serverless-deployment-bucket
  apiGateway:
    binaryMediaTypes:
      - '*/*'

package:
  patterns:
    - '!.git'   # exclude .git file
    - '!.gitignore' # exclude .gitignore file
    - '!README.md'  # exclude README.md file
    - '!LICENSE'   # exclude LICENSE file
    - 'node_modules'
    - 'app.js'
    - 'lambda.js'

functions:
  api:
    handler: lambda.handler
    events:
      - http: ANY /
      - http: "ANY {proxy+}"
